# Generated by Django 5.1.4 on 2024-12-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Don",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prerequisites", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Monstre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("stats", models.JSONField()),
                ("actions", models.JSONField()),
                ("skills", models.JSONField(blank=True, null=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Origine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.TextField()),
                ("sections", models.JSONField()),
                ("tables", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Regle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("sections", models.JSONField()),
                ("tables", models.JSONField(blank=True, null=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Sort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prerequisites", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
    ]
