# Generated by Django 5.1.4 on 2024-12-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_don_monstre_origine_regle_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="monstre",
            name="reactions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
